#162633453 Setup react testing environment
andela/ah-frontend-valkyrie pull request #8
Opened 2019-02-12 18:56 UTC by mycok

**What does this PR do?**

- Setup a react testing environment

**Description of Task to be completed?**
- After cloning the repo, `cd` to the project root folder and run `npm install` to install dependencies.

**How should this be manually tested?**

- Use `npm test` or `yarn test` to run the tests.
- You could also run `yarn/ npm test --coverage` to run tests with coverage.

**Any background context you want to provide?**

- Incase you get dependency errors, delete the node_modules folder along with the package-lock/ yarn-lock files and run `npm/ yarn install` to re-install the relevant packages.

**What are the relevant pivotal tracker stories?**

#162633453('https://www.pivotaltracker.com/story/show/162633453')

2019-02-13 05:00 UTC, jeanjoe requested changes

2019-02-13 05:00 UTC, jeanjoe commented on coverage/clover.xml
> +    <file name="App.js" path="/Users/michael.k/Desktop/ah-react/ah-frontend-valkyrie/src/App.js">
This file path is referencing your local file, it may not be useful here

2019-02-13 05:02 UTC, jeanjoe requested changes

2019-02-13 05:02 UTC, jeanjoe commented on coverage/coverage-final.json
> +{"/Users/michael.k/Desktop/ah-react/ah-frontend-valkyrie/src/App.js": {"path":"/Users/michael.k/Desktop/ah-react/ah-frontend-valkyrie/src/App.js","statementMap":{"0":{"start":{"line":5,"column":4},"e
Please remove this local file path

2019-02-13 06:34 UTC, mubstimor commented on package.json
> +}
missing new line here

2019-02-13 06:34 UTC, mubstimor commented on tests/jest.config.js
> +};
same missing line here

2019-02-13 07:34 UTC, araaliFarooq commented
LGTM

2019-02-13 07:35 UTC, jeanjoe approved these changes

2019-02-13 07:35 UTC, jeanjoe commented
LGTM

2019-02-13 08:51 UTC, Qadriyah commented
LGTM

2019-02-13 09:00 UTC, NabunyaLilian commented
Good work @mycok but please resolve the violations.

2019-02-13 14:53 UTC, merged

2019-02-16 15:41 UTC, araaliFarooq commented
> * npm cache clean



> * You could also run `yarn/ npm test --coverage` to run tests with coverage.

when running tests with **yarn** ` yarn test --coverage` and if using **npm**  the comand is `npm test -- --coverage` .